In [1]:
import pandas as pd 
pd.options.mode.chained_assignment = None
import numpy as np
from astropy.table import Table
import matplotlib.pyplot as plt
import matplotlib
from multiprocessing import Pool
# from profilestats import profile
from scipy.stats import binned_statistic
from funcs.analysis import *
%matplotlib inline

def reader(n_subarray):
    return pd.read_csv('data/merged/{}/lc_{}_{}.csv'.format(obj,band,n_subarray), nrows=None, index_col = ID, dtype = {'catalogue': np.uint8, 'mag_ps': np.float32, 'magerr': np.float32, 'mjd': np.float64, ID: np.uint32})

In [2]:
obj = 'qsos'
ID  = 'uid'
band = 'r'

# Here we load the analysis class. This has various attibutes and methods outlined in /funcs/analysis.py
# Examples:
# Photometry is in dr.df
# Grouped statistics is in dr.grouped
# DR12 VAC properties are in dr.properties
dr = analysis(band, ID)

In [3]:
dr.read_in(reader, redshift=True)
dr.group(keys = ['uid'],read_in=True)

/disk1/hrb/anaconda3/envs/astroconda/lib/python3.6/site-packages/numpy/lib/arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/disk1/hrb/anaconda3/envs/astroconda/lib/python3.6/site-packages/numpy/lib/arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/disk1/hrb/anaconda3/envs/astroconda/lib/python3.6/site-packages/numpy/lib/arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/disk1/hrb/anaconda3/envs/astroconda/lib/python3.6/site-packages/numpy/lib/arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


### Example: finding qsos given ra, dec

> Define a list of ra and decs in the format below

In [4]:
ra_dec = [[0.00531, -2.0332],[359.999615, 3.268586], [359.99851, -0.65588]]

In [5]:
dr.search(ra_dec, 1)

ra       dec  dist_arcsec
uid                                      
6         0.005317 -2.033273     0.265037
526347  359.998520 -0.655884     0.001054
526354  359.999615  3.268586     0.039144

### Grouped statistics of the photometry

In [6]:
dr.df_grouped

mag_mean  mag_median   mag_std  mag_count  magerr_mean       mjd_min  \
uid                                                                             
1       21.333862   21.334082  0.314814         22     0.175084  54741.371761   
2       21.201040   21.304075  0.210223         23     0.135964  54747.352476   
3       20.768782   20.784138  0.190864         36     0.148570  52170.284887   
4       19.807884   19.816252  0.110648         52     0.079946  54764.193704   
5       20.816456   20.876451  0.187447         52     0.139620  53271.313403   
...           ...         ...       ...        ...          ...           ...   
526352  21.296242   21.357853  0.260565         32     0.170418  52909.369624   
526353  19.997482   19.990170  0.130685         75     0.083262  52909.353868   
526354  19.001686   19.024576  0.137761         62     0.048165  54741.213069   
526355  20.121933   20.137114  0.144322         58     0.097981  55119.365472   
526356  20.699917   20.694040  0.166580         55     0.129680  52909.353868   

             mjd_max      mjd_ptp  redshift   mjd_ptp_rf  
uid                                                       
1       58475.144699  3733.772938  2.309000  1128.368975  
2       58487.101042  3739.748566  2.103120  1205.157456  
3       58487.100579  6316.815692  2.497000  1806.352786  
4       58655.441829  3891.248124  1.619000  1485.776298  
5       58657.436319  5386.122916  1.616210  2058.749985  
...              ...          ...       ...          ...  
526352  58486.100787  5576.731163  2.452000  1615.507289  
526353  58657.434954  5748.081086  3.109000  1398.900240  
526354  58655.441829  3914.228759  1.233161  1752.774916  
526355  58653.443866  3534.078394  2.009941  1174.135477  
526356  58653.445706  5744.091838  2.375000  1701.953137  

[523892 rows x 10 columns]

### Load DR12 VAC catalogue

In [7]:
dr.merge_with_catalogue(catalogue='dr12_vac', remove_outliers=True, prop_range_any = {'MBH_MgII':(6,12), 'MBH_CIV':(6,12)})

Number of qsos with lightcurves in r band : 295,605
Number of datapoints in:
SDSS: 730,849
PS: 3,433,377
ZTF: 15,516,963


> Columns included in the value added catalogue:

In [15]:
list(dr.properties.columns)

['mag_mean',
 'mag_median',
 'mag_std',
 'mag_count',
 'magerr_mean',
 'mjd_min',
 'mjd_max',
 'mjd_ptp',
 'redshift',
 'mjd_ptp_rf',
 'Mi',
 'L5100',
 'L5100_err',
 'L3000',
 'L3000_err',
 'L1350',
 'L1350_err',
 'MBH_MgII',
 'MBH_CIV',
 'Lbol',
 'Lbol_err',
 'nEdd',
 'sdss_name',
 'ra',
 'dec',
 'mag_abs_mean']

In [8]:
dr.properties

mag_mean  mag_median   mag_std  mag_count  magerr_mean       mjd_min  \
uid                                                                             
1       21.333862   21.334082  0.314814         22     0.175084  54741.371761   
3       20.768782   20.784138  0.190864         36     0.148570  52170.284887   
4       19.807884   19.816252  0.110648         52     0.079946  54764.193704   
6       19.292772   19.292799  0.074489         71     0.049274  53997.311810   
7       20.025265   19.973215  0.302144         67     0.088740  53997.268272   
...           ...         ...       ...        ...          ...           ...   
526344  21.249285   21.206980  0.171195         15     0.125777  51792.421024   
526348  19.265446   19.264597  0.082411         63     0.057435  54771.319103   
526350  21.442972   21.515675  0.228581         22     0.179135  54771.319103   
526352  21.296242   21.357853  0.260565         32     0.170418  52909.369624   
526353  19.997482   19.990170  0.130685         75     0.083262  52909.353868   

             mjd_max      mjd_ptp  redshift   mjd_ptp_rf  ...  L1350_err  \
uid                                                       ...              
1       58475.144699  3733.772938     2.309  1128.368975  ...      0.111   
3       58487.100579  6316.815692     2.497  1806.352786  ...      0.099   
4       58655.441829  3891.248124     1.619  1485.776298  ...      0.134   
6       58655.441377  4658.129568     1.360  1973.783715  ...     -9.999   
7       58652.457488  4655.189217     2.328  1398.794837  ...      0.082   
...              ...          ...       ...          ...  ...        ...   
526344  56531.481949  4739.060925     2.439  1378.034581  ...      0.115   
526348  58658.412546  3887.093443     2.205  1212.821667  ...      0.092   
526350  58487.100579  3715.781476     2.415  1088.076567  ...      0.125   
526352  58486.100787  5576.731163     2.452  1615.507289  ...      0.093   
526353  58657.434954  5748.081086     3.109  1398.900240  ...      0.103   

        MBH_MgII  MBH_CIV    Lbol  Lbol_err   nEdd           sdss_name  \
uid                                                                      
1         -9.999    8.554  45.701     0.111 -0.953  000000.45+174625.4   
3         -9.999    9.018  46.110     0.099 -1.008  000000.66+145828.8   
4          8.529   -9.999  46.254     0.060 -0.375  000000.97+044947.2   
6          8.897   -9.999  46.222     0.071 -0.775  000001.27-020159.7   
7         -9.999    8.670  46.422     0.082 -0.348  000001.37-011930.0   
...          ...      ...     ...       ...    ...                 ...   
526344    -9.999    9.317  46.103     0.115 -1.314  235959.41-094933.8   
526348     9.121    9.568  46.701     0.076 -0.520  235959.70+084505.2   
526350    -9.999    8.287  45.798     0.125 -0.589  235959.74+100700.4   
526352    -9.999    8.713  45.993     0.093 -0.820  235959.78+285717.0   
526353    -9.999    9.595  46.780     0.103 -0.915  235959.83+344315.0   

                ra        dec  mag_abs_mean  
uid                                          
1         0.001898  17.773739    -23.643374  
3         0.002756  14.974675    -24.378427  
4         0.004052   4.829781    -24.398466  
6         0.005317  -2.033273    -24.535039  
7         0.005746  -1.325009    -24.969766  
...            ...        ...           ...  
526344  359.997573  -9.826069    -23.846890  
526348  359.998774   8.751452    -25.611713  
526350  359.998922  10.116800    -23.631730  
526352  359.999118  28.954734    -23.811476  
526353  359.999303  34.720842    -25.625738  

[281319 rows x 26 columns]

In [9]:
output_notebook()

Loading BokehJS ...

> Example: plot photometry of quasars with uid: [6, 526352, 526344] (currently only r band)

In [16]:
dr.plot_series_bokeh([6,526352,526344])